import { mockDb } from "@/data/mockDb";

export type {
  AddClientVehicleInput,
  AssignTaskInput,
  ChargeClientInput,
  CloseCashSessionInput,
  CreateAttendantInput,
  CreateClientInput,
  CreateManagedUserInput,
  CreateParkingFloorInput,
  CreateParkingSpotInput,
  CreateUnitInput,
  CreateUnitInvitationInput,
  CreateVehicleInput,
  MoveParkingSpotInput,
  OpenCashSessionInput,
  PurgeUnitDataInput,
  RegisterExitInput,
  RemoveUnitMemberInput,
  UpdateClientInput,
  UpdateMyProfileInput,
  UpdateParkingSpotConfigInput,
  UpdateUnitMemberRoleInput,
  UpdateVehicleSpotInput,
} from "@/services/valet.types";

export const valetApi = {
  getVehicles: () => mockDb.getVehicles(),
  getAttendants: () => mockDb.getAttendants(),
  getParkingSpots: () => mockDb.getParkingSpots(),
  getTransactions: () => mockDb.getTransactions(),
  getRevenueData: () => mockDb.getRevenueData(),
  getOccupancyData: () => mockDb.getOccupancyData(),
  getDashboardStats: () => mockDb.getDashboardStats(),
  getActivities: () => mockDb.getActivities(),
  getClients: () => mockDb.getClients(),
  createVehicle: (input: import("@/services/valet.types").CreateVehicleInput) => mockDb.createVehicle(input),
  requestVehicle: (vehicleId: string) => mockDb.requestVehicle(vehicleId),
  registerVehicleExit: (input: import("@/services/valet.types").RegisterExitInput) => mockDb.registerVehicleExit(input),
  assignTask: (input: import("@/services/valet.types").AssignTaskInput) => mockDb.assignTask(input),
  createClient: (input: import("@/services/valet.types").CreateClientInput) => mockDb.createClient(input),
  updateClient: (input: import("@/services/valet.types").UpdateClientInput) => mockDb.updateClient(input),
  addClientVehicle: (input: import("@/services/valet.types").AddClientVehicleInput) => mockDb.addClientVehicle(input),
  chargeClient: (input: import("@/services/valet.types").ChargeClientInput) => mockDb.chargeClient(input),
  createAttendant: (input: import("@/services/valet.types").CreateAttendantInput) => mockDb.createAttendant(input),
  updateVehicleSpot: (input: import("@/services/valet.types").UpdateVehicleSpotInput) => mockDb.updateVehicleSpot(input),
  createParkingSpot: (input: import("@/services/valet.types").CreateParkingSpotInput) => mockDb.createParkingSpot(input),
  updateParkingSpotConfig: (input: import("@/services/valet.types").UpdateParkingSpotConfigInput) => mockDb.updateParkingSpotConfig(input),
  createParkingFloor: (input: import("@/services/valet.types").CreateParkingFloorInput) => mockDb.createParkingFloor(input),
  deleteParkingFloor: (floor: number) => mockDb.deleteParkingFloor(floor),
  deleteParkingSpot: (spotId: string) => mockDb.deleteParkingSpot(spotId),
  moveParkingSpot: (input: import("@/services/valet.types").MoveParkingSpotInput) => mockDb.moveParkingSpot(input),
  getUnits: () => mockDb.getUnits(),
  getCashSessions: () => mockDb.getCashSessions(),
  getCurrentCashSession: () => mockDb.getCurrentCashSession(),
  getUnitMembers: () => mockDb.getUnitMembers(),
  getUnitInvitations: () => mockDb.getUnitInvitations(),
  createUnit: (input: import("@/services/valet.types").CreateUnitInput) => mockDb.createUnit(input),
  createUnitInvitation: (input: import("@/services/valet.types").CreateUnitInvitationInput) => mockDb.createUnitInvitation(input),
  createManagedUser: (input: import("@/services/valet.types").CreateManagedUserInput) => mockDb.createManagedUser(input),
  updateUnitMemberRole: (input: import("@/services/valet.types").UpdateUnitMemberRoleInput) => mockDb.updateUnitMemberRole(input),
  removeUnitMember: (input: import("@/services/valet.types").RemoveUnitMemberInput) => mockDb.removeUnitMember(input),
  purgeUnitData: (input: import("@/services/valet.types").PurgeUnitDataInput) => mockDb.purgeUnitData(input),
  openCashSession: (input: import("@/services/valet.types").OpenCashSessionInput) => mockDb.openCashSession(input),
  closeCashSession: (input: import("@/services/valet.types").CloseCashSessionInput) => mockDb.closeCashSession(input),
  updateMyProfile: (input: import("@/services/valet.types").UpdateMyProfileInput) => mockDb.updateMyProfile(input),
};
