import { localDb } from "@/data/localDb";

export type {
  AddClientVehicleInput,
  AssignTaskInput,
  ChargeClientInput,
  CloseCashSessionInput,
  CreateAttendantInput,
  CreateClientInput,
  CreateManagedUserInput,
  CreateParkingFloorInput,
  CreateParkingSpotInput,
  CreateUnitInput,
  CreateUnitInvitationInput,
  CreateVehicleInput,
  MoveParkingSpotInput,
  OpenCashSessionInput,
  PurgeUnitDataInput,
  RegisterExitInput,
  RemoveUnitMemberInput,
  UpdateClientInput,
  UpdateMyProfileInput,
  UpdateParkingSpotConfigInput,
  UpdateUnitMemberRoleInput,
  UpdateVehicleSpotInput,
} from "@/services/valet.types";

export const valetApi = {
  getVehicles: () => localDb.getVehicles(),
  getAttendants: () => localDb.getAttendants(),
  getParkingSpots: () => localDb.getParkingSpots(),
  getTransactions: () => localDb.getTransactions(),
  getRevenueData: () => localDb.getRevenueData(),
  getOccupancyData: () => localDb.getOccupancyData(),
  getDashboardStats: () => localDb.getDashboardStats(),
  getActivities: () => localDb.getActivities(),
  getClients: () => localDb.getClients(),
  createVehicle: (input: import("@/services/valet.types").CreateVehicleInput) => localDb.createVehicle(input),
  requestVehicle: (vehicleId: string) => localDb.requestVehicle(vehicleId),
  registerVehicleExit: (input: import("@/services/valet.types").RegisterExitInput) => localDb.registerVehicleExit(input),
  assignTask: (input: import("@/services/valet.types").AssignTaskInput) => localDb.assignTask(input),
  createClient: (input: import("@/services/valet.types").CreateClientInput) => localDb.createClient(input),
  updateClient: (input: import("@/services/valet.types").UpdateClientInput) => localDb.updateClient(input),
  addClientVehicle: (input: import("@/services/valet.types").AddClientVehicleInput) => localDb.addClientVehicle(input),
  chargeClient: (input: import("@/services/valet.types").ChargeClientInput) => localDb.chargeClient(input),
  createAttendant: (input: import("@/services/valet.types").CreateAttendantInput) => localDb.createAttendant(input),
  updateVehicleSpot: (input: import("@/services/valet.types").UpdateVehicleSpotInput) => localDb.updateVehicleSpot(input),
  createParkingSpot: (input: import("@/services/valet.types").CreateParkingSpotInput) => localDb.createParkingSpot(input),
  updateParkingSpotConfig: (input: import("@/services/valet.types").UpdateParkingSpotConfigInput) => localDb.updateParkingSpotConfig(input),
  createParkingFloor: (input: import("@/services/valet.types").CreateParkingFloorInput) => localDb.createParkingFloor(input),
  deleteParkingFloor: (floor: number) => localDb.deleteParkingFloor(floor),
  deleteParkingSpot: (spotId: string) => localDb.deleteParkingSpot(spotId),
  moveParkingSpot: (input: import("@/services/valet.types").MoveParkingSpotInput) => localDb.moveParkingSpot(input),
  getUnits: () => localDb.getUnits(),
  getCashSessions: () => localDb.getCashSessions(),
  getCurrentCashSession: () => localDb.getCurrentCashSession(),
  getUnitMembers: () => localDb.getUnitMembers(),
  getUnitInvitations: () => localDb.getUnitInvitations(),
  createUnit: (input: import("@/services/valet.types").CreateUnitInput) => localDb.createUnit(input),
  createUnitInvitation: (input: import("@/services/valet.types").CreateUnitInvitationInput) => localDb.createUnitInvitation(input),
  createManagedUser: (input: import("@/services/valet.types").CreateManagedUserInput) => localDb.createManagedUser(input),
  updateUnitMemberRole: (input: import("@/services/valet.types").UpdateUnitMemberRoleInput) => localDb.updateUnitMemberRole(input),
  removeUnitMember: (input: import("@/services/valet.types").RemoveUnitMemberInput) => localDb.removeUnitMember(input),
  purgeUnitData: (input: import("@/services/valet.types").PurgeUnitDataInput) => localDb.purgeUnitData(input),
  openCashSession: (input: import("@/services/valet.types").OpenCashSessionInput) => localDb.openCashSession(input),
  closeCashSession: (input: import("@/services/valet.types").CloseCashSessionInput) => localDb.closeCashSession(input),
  updateMyProfile: (input: import("@/services/valet.types").UpdateMyProfileInput) => localDb.updateMyProfile(input),
};
